### PR TITLE
Respect base element with fillField()

### LINKED ISSUE #79: fillField() ignores performOn()
Given the following basic form structure:

```html
<label for="title-1">Title</label>
<input id="title-1">

<div class="nested">
    <label for="title-2">Title</label>
    <input id="title-2">
</div>
```

The following snippet will always fill the first `Title` field instead of the second one:

```php
$I->performOn(
    ['class' => 'nested'],
    ActionSequence::build()->fillField('Title', 'Test')
);
```

The reason for this is that `WebDriver::fillField()` uses the internal `WebDriver::findFields()` method and that one always uses `$this->webDriver` (the `RemoteWebDriver` instance) as base instead of `WebDriver::getBaseElement()`.

### PR DESCRIPTION
**Pull request by mbrodala**
Fixes #79

### CODE REVIEW

**Comment by TavoNiievez** [comment]
Hi @mbrodala , Could you please add a test for this change?

It can be something similar to the code example that you related in the issue.

**Comment by mbrodala** [comment]
@TavoNiievez I'd gladly do so if there are instructions how to set up and run the tests.

**Review by TavoNiievez — APPROVED** [review]

**Comment by mbrodala** [comment]
@TavoNiievez Thanks for the approval, I just re-pushed an attempt to actually also test `seeInField()` / `dontSeeInField()` which currently fails. If I don't get it sorted out, I'll revert this since `fillField()` is my focus anyways.

**Comment by mbrodala** [comment]
Reverted as mentioned now to unblock this first.

**Comment by TavoNiievez** [comment]
@mbrodala so this is ready now?
Do you need to update the PR title?

**Comment by mbrodala** [comment]
Yes, it's ready for the issue I mentioned. Technically the other two actions are also fixed but currently I fail to test this properly.

**Comment by TavoNiievez** [comment]
Thank you :)

**Pull request merged**
