### PR TITLE
Reorganizing installation instructions

### PR DESCRIPTION
**Pull request by ThomasLandauer**
...as announced in https://github.com/Codeception/module-webdriver/pull/30#issuecomment-720152810

Open question:
* What's the actual benefit of Selenium?

See https://github.com/Codeception/module-webdriver/pull/31#issue-513707533 for next steps - but I'm waiting for https://github.com/Codeception/codeception.github.com/pull/366 and https://github.com/Codeception/codeception.github.com/pull/367 first...

### CODE REVIEW

**Comment by SamMousa** [comment]
Afaik Selenium allows you to instrument different browsers with a unified api. Originally this was extremely relevant, but nowadays it seems less relevant to me as browsers are standardizing these interfaces themselves.

**Comment by ThomasLandauer** [comment]
> Afaik Selenium allows you to instrument different browsers with a unified api

Well, I would say this is what Codeception is doing :-)

I've been using ChromeDriver without any problems for several years, now trying (for curiosity) with GeckoDriver. However, @DavertMik doesn't really agree, see https://github.com/Codeception/module-webdriver/issues/28#issuecomment-720139366. So I want to find out if there are some *actual* benefits of Selenium we could mention in the docs - or just leave it as is, as a vague additional option.

**Comment by Naktibalda** [comment]
> Well, I would say this is what Codeception is doing :-)

Codeception doesn't do that at all, it uses php-webdriver library for communication with Selenium or other WebDriver protocol implementation.

Selenium project is where the browser testing started. Originaly they implemented browser drivers themselves, but Selenium project pushed driver development to browser developers and WebDriver protocol became W3C protocol and one by one browsers implemented standalone drivers that can work without Selenium.

I don't do any browser testing, but I think that Selenium is still the best option if you want to run your tests in different browsers by changing single line in configuration.

**Comment by ThomasLandauer** [comment]
I would say this is ready to be merged :-)

**Pull request merged**
