### PR TITLE
Test on PHP v7.4

### PR DESCRIPTION
**Pull request by willrowe**
This adds PHP v7.4 as a test target.

### CODE REVIEW

**Comment by Naktibalda** [comment]
Travis wasn't activated for this module.
It uses SemaphoreCI only.
It would be better to raise PR to delete .travis.yaml

**Comment by willrowe** [comment]
@Naktibalda  is Semaphore testing with different PHP versions?

**Comment by Naktibalda** [comment]
It only runs on PHP 5.6 and I don't see a way to make it run on multiple versions of PHP.
If possible, it would be the best to make tests run on Github Actions.

**Comment by willrowe** [comment]
> If possible, it would be the best to make tests run on Github Actions.

Agreed

**Pull request closed without merging**
